### ISSUE TITLE
is:issue is:open 请问在干净模型和后门模型训练的代码中提到了shutil.copy('./cifar_trigger.py', args.checkpoint)和shutil.copy('./cifar.py', args.checkpoint)，但是我看文件中并没有这两个py文件，请问代码是不是有一部分没有公开呢？

### ISSUE THREAD

**Issue by 2539410092** [ZJZAC/Poison-Ink#1]
is:issue is:open 请问在干净模型和后门模型训练的代码中提到了shutil.copy('./cifar_trigger.py', args.checkpoint)和shutil.copy('./cifar.py', args.checkpoint)，但是我看文件中并没有这两个py文件，请问代码是不是有一部分没有公开呢？

**Comment by ZJZAC** [comment]
We rename the 'cifar_trigger.py' and 'cifar.py' as 'backdoored_model.py' and 'clean_model.py', respectively. Thanks, we correct this part.
