### ISSUE TITLE
您好，在看了您的论文后，由于没有找到您的邮箱，所以只能在这进行进行咨询

### ISSUE THREAD

**Issue by 2539410092** [ZJZAC/Poison-Ink#2]
您好，您在论文中有提到，中毒的色彩默认为R:80, G:160, B:80，那如果在不同的类别使用不同的色彩进行中毒操作，即不同标签对应的中毒色彩不同，那么得到的中毒数据集对于最终网络分类影响较大？（网络是否能对不同标签且不同RGB的中毒数据集进行正常分类以及识别？）万分感谢

**Comment by ZJZAC** [comment]
在论文中我们考虑了多label攻击的情况，详情见论文V-F部分，论文链接：https://arxiv.org/pdf/2108.02488.pdf。
