### ISSUE TITLE
about clean.png

### ISSUE THREAD

**Issue by guichen1996** [ZJZAC/Poison-Ink#3]
Excuse me, The image known to this code in IN_GE.py
 **loader = transforms.Compose([transforms.Resize(32), transforms.ToTensor(), ])
    clean_img = Image.open("./dataset/clean.png")
    clean_img = loader(clean_img)**

 is the trigger_ Generation/data/clean. png？“A completely white image”。

**Comment by ZJZAC** [comment]
Yes. Taking CIFAR-10 as an example, it is a 32 X 32 white image (tensor value = 1).

**Comment by guichen1996** [comment]
thankssss
