### ISSUE TITLE
关于隐写性能指标

### ISSUE THREAD

**Issue by guichen1996** [ZJZAC/Poison-Ink#4]
大佬您好，我使用了cifar-10大约25000张图像训练了生成器GE，并选取了“netH_epoch_160,sumloss=4.579761,Hloss=3.551947.pth”第160轮的模型。但在隐写性能指标测试上，我取了1000张cifar10图片psnr与ssim的平均值，但得到的结果是35.36和0.985，远远达不到论文中提到的42与0.99。
     是因为训练数据过少吗？还是应该用别的数据集？希望可以得到您的解答，或者您可以提供一下原始GE模型吗？
     我的邮箱是850420822@qq.com,十分感谢！

**Comment by ZJZAC** [comment]
默认使用的是整个数据集作为训练，在一开始训练的时候只有L1 loss，当鲁棒训练结束后又引入了adv_loss对视觉质量进行了增强，具体可以参照论文中的描述

**Comment by guichen1996** [comment]
好的，十分感谢。
