### ISSUE TITLE
about IN_GE.py

### ISSUE THREAD

**Issue by zsaba** [ZJZAC/Poison-Ink#7]
hello. I was executing this code.  there are number of arguments in  IN_GE.py whose action='store true'. Do i need to mention all these arguments while executing the command?
e.g python IN_GE.py --hostname #exp_name --remark #remark yourself --L1 --vgg_train --rp   --uh --sigmoid --rot
and incremental trainining means:
python IN_GE.py --hostname #exp_name --remark #remark yourself --L1 --vgg_train --rp   --uh --sigmoid --flip

python IN_GE.py --hostname #exp_name --remark #remark yourself --L1 --vgg_train --rp   --uh --sigmoid --crop

python IN_GE.py --hostname #exp_name --remark #remark yourself --L1 --vgg_train --rp   --uh --sigmoid --adv

if we do so , then we have 4 checkpoints where for each best epoch are saved? and for poison generation which augmentation model is used?
or we have to train all at once?
--hostname #exp_name --remark #remark yourself --L1 --vgg_train --rp   --uh --sigmoid --rot --flip --clip --adv

**Comment by zsaba** [comment]
For trigger generation , we have to take Hnet with smallest loss for injecting the trigger ? i took it from using only --rot augmentation. can we take it from training with any augmentation technique  as i trained it using
IN_GE.py --hostname #exp_name --remark #remark yourself --rot
IN_GE.py --hostname #exp_name --remark #remark yourself --flip
IN_GE.py --hostname #exp_name --remark #remark yourself --crop
IN_GE.py --hostname #exp_name --remark #remark yourself --adv
is this correct??

e.g  opt.Hnet = "chk/01cifar10/z_2024-04-24-00_57_19/checkPoints/netH_epoch_199,sumloss=1.793262,Hloss=0.996945.pth"
how did you make advdir?
 #advdir = "/public/zhangjie/ECCV_2020/backdoor/data_processing_zk/data/cifar10_vgg19_totensor_norm_LR0.01/adv_PGD-8/test"  (provided by you) how do we create it? Generating the trigger images by not including the if loop for "adv" is correct or not? as I did not included the if loop but it created the images with _bc.png . can we consider them correct trigger images?

**Comment by ZJZAC** [comment]
Clarification: incremental learning means using --rot; then --rot --flip, wherein --rot shall be preserved for maintaining robustness for the previous augmentation.

After using --rot, you obtained the first model that is robust against rotation. Then, when using --rot --flip, you shall load the model weights of the first model as initialized weights. The subsequent training just follows the same way. After the complete training, you acquired just one final model weights that is robust against all augmentations.

**Comment by zsaba** [comment]
do you mean when i trained the IN_GE.py for 200 epoch i ran the command
python IN_GE.py --hostname #exp_name --remark #remark yourself --rot
 
i got model checkpoints which it is saving. include that in IN_GE.py file  
parser.add_argument('--Hnet', default='',
                    help="path to Hidingnet (to continue training)")
parser.add_argument('--Rnet', default='',
                    help="path to Revealnet (to continue training)")
parser.add_argument('--Dnet', default='',
                    help="path to Discriminator (to continue training)") specify their path here and train it using
python IN_GE.py --hostname #exp_name --remark #remark yourself --rot --flip? and continue that?
when i trained it for --rot i got this  in model checkpoints. do i need to take netH, netD, netR with smallest sumloss?
![Capture](https://github.com/ZJZAC/Poison-Ink/assets/142467358/66e60805-22e8-4a23-a2af-2aeb81df0fb6)

**Comment by zsaba** [comment]
for incremental training, if we use the model robust from previous augmentation , we need to use the load_chk (argument )in command? 
    if opt.load_chk:#indicate whether to load some pre-trained model checkpoints.

        opt.Hnet = opt.Hnet
        opt.Rnet = opt.Rnet                   (from your code)

why it not included the Dnet?

**Comment by ZJZAC** [comment]
Dnet is introduced for adversarial training to enhance the visual quality, which is the last step of the whole incremental training.
