### ISSUE TITLE
about trigger_generation.py

### ISSUE THREAD

**Issue by zsaba** [ZJZAC/Poison-Ink#9]
For trigger generation , we have to take Hnet with smallest loss for injecting the trigger ? i took it from using only --rot augmentation. can we take it from training with any augmentation technique as i trained it using
IN_GE.py --hostname #exp_name --remark #remark yourself --rot
IN_GE.py --hostname #exp_name --remark #remark yourself --flip
IN_GE.py --hostname #exp_name --remark #remark yourself --crop
IN_GE.py --hostname #exp_name --remark #remark yourself --adv
is this correct??

e.g opt.Hnet = "chk/01cifar10/z_2024-04-24-00_57_19/checkPoints/netH_epoch_199,sumloss=1.793262,Hloss=0.996945.pth"
how did you make advdir?
#advdir = "/public/zhangjie/ECCV_2020/backdoor/data_processing_zk/data/cifar10_vgg19_totensor_norm_LR0.01/adv_PGD-8/test" (provided by you) how do we create it? Generating the trigger images by not including the if loop for "adv" is correct or not? as I did not included the if loop but it created the images with _bc.png . can we consider them correct trigger images?

**Comment by ZJZAC** [comment]
See the feedback [#7](https://github.com/ZJZAC/Poison-Ink/issues/7#issuecomment-2089483179)

**Comment by zsaba** [comment]
which command i need to run ?
IN_GE.py --hostname #exp_name --remark #remark yourself --rot
or
IN_GE.py --hostname #exp_name --remark #remark yourself  --L1 --rp --uh  --sigmoid --noise --rot

**Comment by zsaba** [comment]
hello. I need your guidance . i have commented on that issues kindly give your feedback.

Thank you
________________________________

**Comment by ZJZAC** [comment]
IN_GE.py --hostname #exp_name --remark #remark yourself --rot  is okay.

Other options can be tried for ablation studies.

**Comment by zsaba** [comment]
when i generated the triggered input, as the target class is airplane, it is also creating triggers images from airplane class as well. is this happened in your experiment too?
